#include "platform.h"

#if defined(ANALYZER_STM32F446)

#include "app_config.h"
#include "FreeRTOS.h"
#include "task.h"
#include "stm32f4xx_hal.h"

#include <math.h>

/* Handles and initializers are generated by the CubeMX project. */
extern ADC_HandleTypeDef hadc1;
extern ADC_HandleTypeDef hadc2;
extern DAC_HandleTypeDef hdac;
extern TIM_HandleTypeDef htim2;
extern TIM_HandleTypeDef htim5;
extern UART_HandleTypeDef huart2;
extern IWDG_HandleTypeDef hiwdg;
extern void SystemClock_Config(void);
extern void MX_GPIO_Init(void);
extern void MX_DMA_Init(void);
extern void MX_ADC1_Init(void);
extern void MX_ADC2_Init(void);
extern void MX_DAC_Init(void);
extern void MX_TIM2_Init(void);
extern void MX_TIM5_Init(void);
extern void MX_USART2_UART_Init(void);

#define ADC_DMA_HALF_FRAMES ADC_DMA_FRAMES_PER_HALF
#define ADC_DMA_TOTAL_FRAMES (2u * ADC_DMA_HALF_FRAMES)
#define DAC_TONE_BIN 10u

static uint32_t adc_dma_words[ADC_DMA_TOTAL_FRAMES];
static uint32_t dac_tone[ANALYZER_FFT_SIZE];
static TaskHandle_t adc_waiter;
static TaskHandle_t uart_waiter;
static volatile uint32_t completed_generation;
static volatile uint32_t completed_half;
static volatile uint32_t adc_overrun_count;
static bool test_signal_running;
static bool watchdog_reset_detected;

static void enable_cycle_counter(void) {
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0u;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;
}

void platform_init(void) {
    HAL_Init();
    watchdog_reset_detected =
        __HAL_RCC_GET_FLAG(RCC_FLAG_IWDGRST) != RESET;
    __HAL_RCC_CLEAR_RESET_FLAGS();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_DMA_Init();
    MX_ADC1_Init();
    MX_ADC2_Init();
    MX_DAC_Init();
    MX_TIM2_Init();
    MX_TIM5_Init();
    MX_USART2_UART_Init();
    enable_cycle_counter();
    configASSERT(HAL_TIM_Base_Start(&htim5) == HAL_OK);
}

uint32_t platform_time_us(void) {
    return __HAL_TIM_GET_COUNTER(&htim5);
}

uint32_t platform_cycle_count(void) {
    return DWT->CYCCNT;
}

uint32_t platform_core_clock_hz(void) {
    return SystemCoreClock;
}

bool platform_watchdog_reset_detected(void) {
    return watchdog_reset_detected;
}

static bool start_dac_loopback_tone(void) {
#if ENABLE_DAC_LOOPBACK_TEST
    const float two_pi = 6.2831853071795864769f;
    for (size_t i = 0u; i < ANALYZER_FFT_SIZE; ++i) {
        const float phase = two_pi * (float)(DAC_TONE_BIN * i) /
                            (float)ANALYZER_FFT_SIZE;
        /* 1.65 V offset, approximately 1.32 V peak-to-peak. */
        dac_tone[i] = (uint32_t)lroundf(2048.0f + 819.0f * sinf(phase));
    }
    test_signal_running = HAL_DAC_Start_DMA(
        &hdac, DAC_CHANNEL_1, dac_tone, ANALYZER_FFT_SIZE,
        DAC_ALIGN_12B_R) == HAL_OK;
    return test_signal_running;
#else
    test_signal_running = false;
    return true;
#endif
}

bool platform_adc_start(void) {
    adc_waiter = xTaskGetCurrentTaskHandle();
    completed_generation = 0u;
    completed_half = 0u;
    adc_overrun_count = 0u;
    if (!start_dac_loopback_tone()) return false;
    /* In dual regular mode the slave ADC must be enabled before the master. */
    if (HAL_ADC_Start(&hadc2) != HAL_OK) return false;
    if (HAL_ADCEx_MultiModeStart_DMA(&hadc1, adc_dma_words,
                                     ADC_DMA_TOTAL_FRAMES) != HAL_OK) {
        (void)HAL_ADC_Stop(&hadc2);
        return false;
    }
    /* TIM2 TRGO clocks ADC1, ADC2, and DAC1 from the same 100 kHz event. */
    if (HAL_TIM_Base_Start(&htim2) != HAL_OK) {
        (void)HAL_ADCEx_MultiModeStop_DMA(&hadc1);
        (void)HAL_ADC_Stop(&hadc2);
        return false;
    }
    return true;
}

bool platform_test_signal_active(void) {
    return test_signal_running;
}

static void publish_completed_half(uint32_t half) {
    BaseType_t wake = pdFALSE;
    completed_half = half;
    ++completed_generation;
    if (adc_waiter != NULL) vTaskNotifyGiveFromISR(adc_waiter, &wake);
    portYIELD_FROM_ISR(wake);
}

void HAL_ADC_ConvHalfCpltCallback(ADC_HandleTypeDef *hadc) {
    if (hadc != NULL && hadc->Instance == ADC1) publish_completed_half(0u);
}

void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc) {
    if (hadc != NULL && hadc->Instance == ADC1) publish_completed_half(1u);
}

void HAL_ADC_ErrorCallback(ADC_HandleTypeDef *hadc) {
    if (hadc != NULL && hadc->Instance == ADC1) ++adc_overrun_count;
}

bool platform_adc_wait_block(adc_dma_block_t *block, uint32_t timeout_ms) {
    if (block == NULL) return false;
    const uint32_t notifications = ulTaskNotifyTake(
        pdTRUE, pdMS_TO_TICKS(timeout_ms));
    if (notifications == 0u) return false;
    if (notifications > 1u) adc_overrun_count += notifications - 1u;
    taskENTER_CRITICAL();
    const uint32_t half = completed_half;
    block->generation = completed_generation;
    taskEXIT_CRITICAL();
    block->packed_samples = &adc_dma_words[half * ADC_DMA_HALF_FRAMES];
    block->timestamp_us = platform_time_us();
    block->frames = ADC_DMA_HALF_FRAMES;
    return true;
}

uint32_t platform_adc_overruns(void) {
    return adc_overrun_count;
}

uint32_t platform_adc_generation(void) {
    return completed_generation;
}

bool platform_uart_write_dma(const uint8_t *data, size_t length,
                             uint32_t timeout_ms) {
    if (data == NULL || length == 0u || length > UINT16_MAX) return false;
    uart_waiter = xTaskGetCurrentTaskHandle();
    if (HAL_UART_Transmit_DMA(&huart2, (uint8_t *)data,
                              (uint16_t)length) != HAL_OK) {
        uart_waiter = NULL;
        return false;
    }
    const bool completed = ulTaskNotifyTake(
        pdTRUE, pdMS_TO_TICKS(timeout_ms)) != 0u;
    uart_waiter = NULL;
    if (!completed) (void)HAL_UART_AbortTransmit(&huart2);
    return completed;
}

void HAL_UART_TxCpltCallback(UART_HandleTypeDef *huart) {
    if (huart != NULL && huart->Instance == USART2) {
        BaseType_t wake = pdFALSE;
        if (uart_waiter != NULL) {
            vTaskNotifyGiveFromISR(uart_waiter, &wake);
        }
        portYIELD_FROM_ISR(wake);
    }
}

void platform_watchdog_start(uint32_t timeout_ms) {
    (void)timeout_ms;
    hiwdg.Instance = IWDG;
    hiwdg.Init.Prescaler = IWDG_PRESCALER_32;
    hiwdg.Init.Reload = 1000u;
    configASSERT(HAL_IWDG_Init(&hiwdg) == HAL_OK);
}

void platform_watchdog_feed(void) {
    (void)HAL_IWDG_Refresh(&hiwdg);
}

void platform_idle(void) {
    __DSB();
    __WFI();
}

#endif
